ajax_django_form/human/urls.py
from django.conf.urls import url
from . import views


urlpatterns =  [
    url(r'^$', views.list_human, name='view_human'),
    url(r'^create/$', views.create_human, name='create_user'),
    url(r'^update/$', views.update_human, name='update_user'),
]

ajax_django_form/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    url(r'^human/', include('ajax_django_form.human.urls', namespace='human'))
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT})
    ]

ajax_django_form/human/models.py
from decimal import Decimal
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils.translation import ugettext as _


class PunyHuman(models.Model):
    SEX_CHOICES = (
        ('male', _('Male')),
        ('female', _('Female')),
        ('other', _('Other')),
        ('yes_please', _('Yes please :D')),
    )

    name = models.CharField(max_length=70, verbose_name=_('name'))
    weight = models.DecimalField(null=True, blank=True, verbose_name=_('weight'), help_text=_('Weight in pounds.'),
                                 validators=[MinValueValidator(Decimal('0.01'))], decimal_places=2, max_digits=6)
    birthday = models.DateField(verbose_name=_('birthday'))
    sex = models.CharField(max_length=20, choices=SEX_CHOICES)

    level_of_hotness = models.PositiveSmallIntegerField(verbose_name=('level of hotness'),
                                                        help_text=_('Higher is hotter'),
                                                        validators=[MinValueValidator(1),
                                                                    MaxValueValidator(10),])

ajax_django_form/human/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Button, Submit
from django import forms
from django.core.exceptions import ValidationError
from ajax_django_form.human.models import PunyHuman
from django.utils.translation import ugettext as _


class PunyHumanForm(forms.ModelForm):

    class Meta:
        model = PunyHuman
        excludes = []

    def clean_level_of_hotness(self):
        level = self.cleaned_data['level_of_hotness']
        if level < 2:
            raise ValidationError(_('Don\'t be so mean!'))
        return level

    def __init__(self, *args, **kwargs):
        helper = FormHelper()
        helper.form_method = 'POST'
        helper.form_action = 'create/'
        helper.form_class = 'dj-ajax-form'
        helper.add_input(Button('reset', _('Reset'), css_class='btn btn-warning'))
        helper.add_input(Submit('create', _('Create')))

        self.helper = helper
        super().__init__(*args, **kwargs)


class PunyHumanUpdateForm(PunyHumanForm):
    id = forms.IntegerField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        helper = FormHelper()
        helper.form_method = 'POST'
        helper.form_action = 'update/'
        helper.form_class = 'dj-ajax-form'
        helper.add_input(Button('reset', _('Reset'), css_class='btn btn-warning'))
        helper.add_input(Submit('update', _('Update')))
        self.helper = helper

ajax_django_form/human/views.py
from django.shortcuts import render
from ajax_django_form.human.models import PunyHuman


def list_human(request):
    context = {
        'data': PunyHuman.objects.all()
    }

    return render(request, 'human/view_human.html', context)


def create_human(request):
    return None


def update_human(request):
    return None

ajax_django_form/human/templates/human/view_human.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}
    {% autoescape on %}
        <div class="menu">
            <button class="btn btn-primary" id="btn-new"><span class="glyphicon glyphicon-plus"></span> {% trans 'New'|force_escape %}</button>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">{% trans 'ID' %}</th>
                    <th scope="col">{% trans 'Name' %}</th>
                    <th scope="col">{% trans 'Weight' %}</th>
                    <th scope="col">{% trans 'Birthday' %}</th>
                    <th scope="col">{% trans 'Sex' %}</th>
                    <th scope="col">{% trans 'Edit' %}</th>
                    <th scope="col">{% trans 'Delete' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for row in data.rows %}
                    <tr>
                        <td>{{ row.id }}</td>
                        <td>{{ row.name }}</td>
                        <td>{{ row.weight }}</td>
                        <td>{{ row.birthday }}</td>
                        <td>{{ row.get_sex_display }}</td>
                        <td>
                            <button class="btn btn-primary btn-xs btn-edit-puny-human" data-id="{{ row.id }}" title="{% trans 'Edit Puny Human' %}">
                                <span class="glyphicon glyphicon-edit"></span> {% trans 'Edit' %}
                            </button>
                        </td>
                        <td>
                            <button class="btn btn-primary btn-xs btn-delete-puny-human" data-id="{{ row.id }}" title="{% trans 'Delete Puny Human' %}">
                                <span class="glyphicon glyphicon-trash"></span> {% trans 'Delete' %}
                            </button>
                        </td>
                    </tr>
                {% empty %}
                    <tr><td colspan="100">{% trans 'No records found!' %}</td></tr>
                {% endfor %}
            </tbody>
        </table>
    {% endautoescape %}

{% endblock %}

ajax_django_form/templates/ajax_form.html
<!DOCTYPE html>
<html lang="en">
{% load crispy_forms_tags %}
<head>
    <meta charset="UTF-8">
    <title>Django Ajax Form</title>
</head>
<body>
    <div class="dj-ajax-form-result">
        {% block form_display %}
            {% crispy form %}
        {% endblock %}

        {% block form_footer %}
            {{ form.media }}
        {% endblock %}
    </div>
</body>
</html>

ajax_django_form/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title|default:'Ajax Django Form' }}</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap-theme.min.css' %}">

    <link rel="stylesheet" href="{% static 'vendor/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-dialog/bootstrap-dialog.css' %}">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    {% block body %}
        <main>
            {% block main %}
            {% endblock %}
        </main>
    {% endblock %}

    <script src="{% static 'vendor/jquery/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <script src="{% static 'vendor/block-ui/jquery.blockUI.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap-datetimepicker/js/moment-with-locales.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap-dialog/bootstrap-dialog.min.js' %}"></script>
    <script src="{% static 'vendor/jquery-form/jquery.form.min.js' %}"></script>

    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>